### ISSUE TITLE
New forge, and crashing

### ISSUE THREAD

**Issue by Sasikaa** [TeamAmeriFrance/Guide-API#40] opened 2016-08-01 16:23 UTC
forge-1.10.2-12.18.1.2043-universal
Guide-API-1.9.4-2.0.0-40
BloodMagic-1.9.4-2.0.3-53

Here is my crash report:

http://pastebin.com/Lc4UpMjY

**Comment by TehNut** [comment] 2016-08-01 22:40
Is this reproduceable?

**Comment by tali713** [comment] 2016-08-02 04:13
Reproduced, with 2044, just Guide API
http://pastebin.com/raw/T6uCQfWi

Probably a duplicate of #38

**Comment by TehNut** [comment] 2016-08-02 04:31
@tali713 That is actually a different crash. Yours is caused by #38.

**Comment by tali713** [comment] 2016-08-02 16:12
Aha, I see.  I still think the two bugs are actually the same bug, though it is peculiar that they raise a different initial error.

Once more with just blood magic and guide-api:
http://pastebin.com/KBCKw9Hk

**Comment by TehNut** [comment] 2016-08-02 16:18
All I can really say is to downgrade Forge until its fixed. I'll probably be doing a PR for it today

**Comment by TehNut** [comment] 2016-08-02 23:08
Please try with Forge build 2045.

**Comment by maxanier** [comment] 2016-08-16 17:11
Still got the same problem:

```
java.lang.NullPointerException
    at net.minecraftforge.fml.common.registry.PersistentRegistryManager.makeDelegate(PersistentRegistryManager.java:694) ~[PersistentRegistryManager.class:?]
    at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.<init>(IForgeRegistryEntry.java:67) ~[IForgeRegistryEntry$Impl.class:?]
    at amerifrance.guideapi.api.impl.Book.<init>(Book.java:16) ~[Book.class:1.9.4-2.0.0-40]
```

with latest Forge build (v12.18.1.2065) and latest GuideApi version 1.9.4-2.0.0-40.
Tested in dev/deobf environment, not sure about normal one.

**Comment by maxanier** [comment] 2016-08-16 17:27
Ok, solved the problem. If I create the book during INIT instead of PRE_INIT everything seems to work fine.

Please change the instructions here :)
[https://guide-api.readthedocs.io/en/latest/createabook/basic/](https://guide-api.readthedocs.io/en/latest/createabook/basic/)

**Comment by TehNut** [comment] 2016-08-16 18:01
No. Pre is correct init is not. Are you loading before gapi?

**Comment by TehNut** [comment] 2016-08-16 18:26
In the future, I will cause a more informative crash if a book is registered too early (before gapi hits preinit) or too late (during init or later).

**Comment by maxanier** [comment] 2016-08-16 18:46
Ok sorry, messed that up, totally forgot to set the load order.
Works fine during pre-init now, thanks :)

**Comment by TehNut** [comment] 2016-08-16 22:45
615504ad79c243f380b5f3ee05b34c7dac157f04

**Closed as completed by TehNut** 2016-08-16 22:45 UTC
